### ISSUE TITLE
What is the official home page of afio?

### ISSUE THREAD

**Issue by kini** [kholtman/afio#12]
The README says to check http://members.chello.nl/k.holtman/afio.html for the latest version, but that web page doesn't exist. Is this GitHub repository now the official home page of `afio`?

**Comment by kholtman** [comment]
Thanks for your question.

The web page you mention is indeed gone, my internet provider dropped the service of hosting these pages after merging with another provider.  I only recently found out.

The GitHub repository is now the official home page of afio.  I need to update things across the documentation to make that more clear, but have not yet had the time. I guess I can do a quick fix to the README on GitHub at least, without doing a new version-numbered release of all documentation, so I will do so now.

**Comment by kini** [comment]
Thanks, I appreciate it! No hurry to make changes in the repo, I just wanted an official word from you about it so I can change the metadata in the NixOS package for `afio`.
